name: Paypara
type: php
docroot: ""
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- dev.paypara.dev
- demo.paypara.dev
- api.dev.paypara.dev
- pay.dev.paypara.dev
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: true
upload_dir: public/
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
